name: Run PowerShell Script

on:
  push:
    branches: [ master ]

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PowerShell script
        run: ./test.ps1
        shell: pwsh

