name: First Windows Workflow

on:
  push:
    branches: [ master ]

jobs:
  hello:
    runs-on: windows-latest

    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions on Windows!! I have definitely done something!"
